#!/bin/bash
# SPDX-FileCopyrightText: © 2008 Oprea Dan
# SPDX-FileCopyrightText: © 2012 Germar Reitze
# SPDX-FileCopyrightText: © 2022 Jürgen Altfeld (aryoda)
# SPDX-FileCopyrightText: © 2023 Christian Buhtz <c.buhtz@posteo.jp>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of the program "Back In time" which is released under GNU
# General Public License v2 (GPLv2). See LICENSES directory or go to
# <https://spdx.org/licenses/GPL-2.0-or-later.html>.
#
# Updates all version numbers using the VERSION file
VERSION=$(cat VERSION)
BUILD_INFO_PATH="common/buildinfo.py"
GIT_HASH=''

update_app_version () {
  echo "Update '$1'"
  sed --expression="s/^\(\s*\)__version__ = '.*'$/\1__version__ = '$VERSION'/" --in-place "$1"
}

if [[ $VERSION == *-dev ]]
then
    GIT_HASH=$(git rev-parse --short HEAD)
    echo "# Auto-generated by $0. Do not edit." > "$BUILD_INFO_PATH"
    echo "git_hash = '$GIT_HASH'" >> "$BUILD_INFO_PATH"
else
    rm --force "$BUILD_INFO_PATH"

    update_app_version common/version.py
fi

echo VERSION: "$VERSION"
if [[ -n $GIT_HASH ]]
then
    echo GIT_HASH: "$GIT_HASH"
fi

# MAINTAINER="Germar Reitze <germar.reitze@gmail.com>"
# MAINTAINER="BIT Team <dan@le-web.org>"
MAINTAINER="BIT Team <bit-dev@python.org>"
