.TH backintime-qt4 1 "July 2015" "version 1.1.7" "USER COMMANDS"
.SH NAME
backintime-qt4 \- a simple backup tool.
.SH SYNOPSIS
.B backintime-qt4
[ \-\-profile NAME |
\-\-profile\-id ID ] 
[ \-\-keep\-mount ] 
[ \-\-quiet ] 
[ \-\-config PATH ] 
[ \-\-checksum ] 
[ \-\-help | \-h ] 
[ \-\-version ] 
[ \-\-license ]
{ backup | backup\-job |
snapshots\-path |
snapshots\-list | snapshots\-list\-path |
last\-snapshot | last\-snapshot\-path |
unmount |
benchmark-cipher [FILE-SIZE] |
pw\-cache [start|stop|restart|reload|status] |
decode [PATH] |
remove[\-and\-do\-not\-ask\-again] [SNAPSHOT_ID] |
restore [WHAT [WHERE [SNAPSHOT_ID]]] |
check-config }

.SH DESCRIPTION
Back In Time is a simple backup tool for Linux. This is the Qt4 version.
For more information about Back In Time see backintime man page.
.PP
If you want to run it as root you need to use 'pkexec backintime-qt4'.
.SH OPTIONS
.TP
\-\-profile NAME
select profile by name
.TP
\-\-profile\-id ID
select profile by id
.TP
\-\-keep\-mount
Don't unmount on exit. Only valid with \fIsnapshots\-path\fR, \fIsnapshots\-list\-path\fR and 
\fIlast\-snapshot\-path\fR.
.TP
\-\-quiet
suppress status messages on standard output.
.TP
\-\-config PATH
read config from PATH.
.TP
\-\-checksum
force to use checksum for checking if files have been changed. This is the same 
as 'Use checksum to detect changes' in Options. But you can use this to 
periodically run checksums from cronjobs.
.TP
\-h, \-\-help
display a short help
.TP
\-v, \-\-version
show version
.TP
\-\-license
show license

.SH COMMANDS
.TP
backup | \-b | \-\-backup
take a snapshot now (if needed) 
.TP
backup\-job | \-\-backup\-job
take a snapshot (if needed) depending on schedule rules (used for cron jobs).
Back In Time will run in background for this.
.TP
snapshots\-path | \-\-snapshots\-path
display path where is saves the snapshots (if configured) 
.TP
snapshots\-list | \-\-snapshots\-list
display the list of snapshot IDs (if any)
.TP
snapshots\-list\-path | \-\-snapshots\-list\-path
display the paths to snapshots (if any)
.TP
last\-snapshot | \-\-last\-snapshot
display last snapshot ID (if any)
.TP
last\-snapshot\-path | \-\-last\-snapshot\-path
display the path to the last snapshot (if any)
.TP
unmount | \-\-unmount
Unmount the profile.
.TP
benchmark-cipher | \-\-benchmark-cipher [FILE-SIZE]
Show a benchmark of all ciphers for ssh transfer.
.TP
pw\-cache | \-\-pw\-cache [start|stop|restart|reload|status]
Control the Password Cache Daemon. If no argument is given the Password Cache 
will start in foreground.
.TP
decode | \-\-decode [PATH]
decode encrypted PATH. If no PATH is given Back In Time will read paths from 
standard input.
.TP
remove[\-and\-do\-not\-ask\-again] | \-\-remove[\-and\-do\-not\-ask\-again] [SNAPSHOT_ID]
Remove the snapshot. If SNAPSHOT_ID is missing it will be prompted. SNAPSHOT_ID 
can be an index (starting with 0 for the last snapshot) or the exact SnapshotID 
(19 caracters like '20130606-230501-984'). 
\fIremove\-and\-do\-not\-ask\-again\fR will remove the snapshot immediately. 
Be careful with this!
.TP
restore | \-\-restore [WHAT [WHERE [SNAPSHOT_ID]]]
Restore file WHAT to path WHERE from snapshot SNAPSHOT_ID. If arguments are 
missing they will be prompted. To restore to the original path WHERE can be an 
empty string '' or just press Enter at the prompt. SNAPSHOT_ID can be an index 
(starting with 0 for the last snapshot) or the exact SnapshotID 
(19 caracters like '20130606-230501-984')
.TP
check-config
Verify the profile in config, create snapshot path and crontab entries.

.SH SEE ALSO
backintime, backintime-config.
.PP
Back In Time also has a website: http://backintime.le\-web.org
.SH AUTHOR
This manual page was written by BIT Team(<bit\-team@lists.launchpad.net>).
