.TH backintime-qt 1 "August 2024" "version 1.5.3-dev.3e80feee" "USER COMMANDS"
.SH NAME
backintime-qt \- a simple backup tool.
.SH SYNOPSIS
.B backintime-qt
[\-\-checksum]
[\-\-config PATH]
[\-\-debug]
[\-\-delete]
[\-\-help | \-h]
[\-\-keep\-mount]
[\-\-license]
[\-\-local\-backup |
\-\-no\-local\-backup]
[\-\-no\-crontab]
[\-\-only\-new]
[\-\-profile NAME |
\-\-profile\-id ID]
[\-\-quiet]
[\-\-share\-path PATH]
[\-\-version]

{ backup | backup\-job |
benchmark-cipher [FILE-SIZE] |
check-config |
decode [PATH] |
last\-snapshot | last\-snapshot\-path |
pw\-cache [start|stop|restart|reload|status] |
remove[\-and\-do\-not\-ask\-again] [SNAPSHOT_ID] |
restore [WHAT [WHERE [SNAPSHOT_ID]]] |
shutdown |
smart\-remove |
snapshots\-list | snapshots\-list\-path |
snapshots\-path |
unmount }

.SH DESCRIPTION
Back In Time is a simple backup tool for Linux. This is the Qt version.
For more information about Back In Time see backintime man page.
.PP
If you want to run it as root you need to use 'backintime-qt_polkit'.
.SH OPTIONS
.TP
\-\-checksum
Force to use checksum for checking if files have been changed. This is the same
as 'Use checksum to detect changes' in Options. But you can use this to
periodically run checksums from cronjobs. Only valid with \fIbackup\fR,
\fIbackup-job\fR and \fIrestore\fR.
.TP
\-\-config PATH
Read config from PATH. Default = ~/.config/backintime/config
.TP
--debug
Show debug messages.
.TP
--delete
Restore and delete newer files which are not in the snapshot.
WARNING: deleting files in filesystem root could break your whole system!!!
Only valid with \fIrestore\fR.
.TP
\-h, \-\-help
Display a short help
.TP
\-\-keep\-mount
Don't unmount on exit. Only valid with \fIsnapshots\-path\fR, \fIsnapshots\-list\-path\fR and
\fIlast\-snapshot\-path\fR.
.TP
\-\-license
Show license
.TP
--local-backup
Create backup files before changing local files.
Only valid with \fIrestore\fR.
.TP
--no-crontab
Do not install crontab entries.
Only valid with \fIcheck-config\fR.
.TP
--no-local-backup
Temporary disable creation of backup files before changing local files.
Only valid with \fIrestore\fR.
.TP
--only-new
Only restore files which does not exist or are newer than those in destination.
Using "rsync --update" option.
Only valid with \fIrestore\fR.
.TP
\-\-profile NAME
Select profile by name
.TP
\-\-profile\-id ID
Select profile by id
.TP
\-\-quiet
Suppress status messages on standard output.
.TP
\-\-share\-path PATH
Write runtime data (locks, messages, log and mountpoints) to PATH.
.TP
\-v, \-\-version
Show version

.SH COMMANDS
.TP
backup | \-b | \-\-backup
Take a snapshot now.
.TP
backup\-job | \-\-backup\-job
Take a snapshot (if needed) depending on schedule rules (used for cron jobs).
Back In Time will run in background for this.
.TP
benchmark-cipher | \-\-benchmark-cipher [FILE-SIZE]
Show a benchmark of all ciphers for ssh transfer.
.TP
check-config
Verify the profile in config, create snapshot path and crontab entries.
.TP
decode | \-\-decode [PATH]
Decode encrypted PATH. If no PATH is given Back In Time will read paths from
standard input.
.TP
last\-snapshot | \-\-last\-snapshot
Display last snapshot ID (if any)
.TP
last\-snapshot\-path | \-\-last\-snapshot\-path
Display the path to the last snapshot (if any)
.TP
pw\-cache | \-\-pw\-cache [start|stop|restart|reload|status]
Control the Password Cache Daemon. If no argument is given the Password Cache
will start in foreground.
.TP
remove[\-and\-do\-not\-ask\-again] | \-\-remove[\-and\-do\-not\-ask\-again] [SNAPSHOT_ID]
Remove the snapshot. If SNAPSHOT_ID is missing it will be prompted. SNAPSHOT_ID
can be an index (starting with 0 for the last snapshot) or the exact SnapshotID
(19 characters like '20130606-230501-984').
\fIremove\-and\-do\-not\-ask\-again\fR will remove the snapshot immediately.
Be careful with this!
.TP
restore | \-\-restore [WHAT [WHERE [SNAPSHOT_ID]]]
Restore file WHAT to path WHERE from snapshot SNAPSHOT_ID. If arguments are
missing they will be prompted. To restore to the original path WHERE can be an
empty string '' or just press Enter at the prompt. SNAPSHOT_ID can be an index
(starting with 0 for the last snapshot) or the exact SnapshotID
(19 characters like '20130606-230501-984')
.TP
shutdown
Shutdown the computer after the snapshot is done.
.TP
smart\-remove
Remove snapshots based on the configured Smart-Remove pattern.
.TP
snapshots\-list | \-\-snapshots\-list
Display the list of snapshot IDs (if any)
.TP
snapshots\-list\-path | \-\-snapshots\-list\-path
Display the paths to snapshots (if any)
.TP
snapshots\-path | \-\-snapshots\-path
Display path where is saves the snapshots (if configured)
.TP
unmount | \-\-unmount
Unmount the profile.
.SH SEE ALSO
.BR backintime-qt (1),
.BR backintime-config (1),
.BR backintime-askpass (1)
.PP
\fBBack In Time\fP project website: https://github.com/bit-team/backintime
.PP
\fBBack In Time\fP mailing list: https://mail.python.org/mailman3/lists/bit-dev.python.org
.SH AUTHOR
\fBBack In Time\fP Team
