////
SPDX-FileCopyrightText: © 2012 Germar Reitze
SPDX-FileCopyrightText: © 2013 Oprea Dan
SPDX-FileCopyrightText: © 2022 Jürgen Altfeld (aryoda)
SPDX-FileCopyrightText: © 2023 Christian Buhtz <c.buhtz@posteo.jp>

SPDX-License-Identifier: GPL-2.0-or-later

This file is part of the program "Back In Time" which is released under GNU
General Public License v2 (GPLv2). See LICENSES directory or go to
<https://spdx.org/licenses/GPL-2.0-or-later.html>.
////
= backintime-qt(1)
:doctype: manpage
:manmanual: Back In Time
:mansource: backintime-qt {version}
:man-linkstyle: pass:[blue R < >]

== NAME

backintime-qt - Graphical Frontend for Back In Time

== SYNOPSIS

*backintime-qt*
[--help | -h]
[--version]
[--license]
[--debug]
<command>
[<args>]

== DESCRIPTION

A comfortable and well-configurable graphical Frontend for incremental
backups. Modified files are transferred, while unchanged files are linked to
the new folder using rsync's hard link feature, saving storage space.
Restoring is straightforward via file manager, command line or *Back In Time*
itself.

For more information about *Back In Time* see its command-line interface
*backintime*(1). Options and commands are passed through to *backintime* (1).

If you want to run it as root please use `backintime-qt_polkit`.


== OPTIONS

*-h*, *--help*::  Display a short help.

*-v*, *--version*:: Show version.

*--license*:: Show license.

*--debug*::   Show debug messages.

See *backintime* (1) for more options.

== COMMANDS

See *backintime* (1) for commands.


== SEE ALSO

*backintime*(1), *backintime-config*(1), *backintime-askpass*(1)

*Back In Time* project website: https://github.com/bit-team/backintime

*Back In Time* mailing list: https://mail.python.org/mailman3/lists/bit-dev.python.org

== AUTHOR

*Back In Time* Team
