.TH backintime-askpass 1 "August 2024" "version 1.5.3-dev.3e80feee" "USER COMMANDS"
.SH NAME
backintime-askpass \- a simple backup tool for Linux.
.PP
This is the command line tool for piping passwords into ssh/sshfs and encfs.
.SH SYNOPSIS
.B backintime-askpass

.SH DESCRIPTION
Back In Time is a simple backup tool for Linux. This is a helper tool for
piping passwords into ssh/sshfs and encfs. Options will will be read from
environ variables. It doesn't provide any useful enduser service.


.SH ENVIRON
.TP
ASKPASS_PROFILE_ID
Back In Time Profile-ID.
.TP
ASKPASS_MODE
Backup mode (or backend).  Take a look at 'man backintime-config'
section \fIprofile<N>.snapshots.mode\fR
.TP
ASKPASS_TEMP
Temp FIFO socket used to pipe the password
.SH SEE ALSO
.BR backintime (1),
.BR backintime-qt (1),
.BR backintime-config (1),
.PP
\fBBack In Time\fP project website: https://github.com/bit-team/backintime
.PP
\fBBack In Time\fP mailing list: https://mail.python.org/mailman3/lists/bit-dev.python.org
.SH AUTHOR
\fBBack In Time\fP Team
