#!/bin/sh

#    Back In Time
#    Copyright (C) 2008-2022 Oprea Dan, Bart de Koning, Richard Bailey, Germar Reitze
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Location of this script
CUR_PATH="$(dirname $(readlink -m $0))"

# Was this script started in the source code folder (normally during development)?
if [ -f "${CUR_PATH}/backintime.py" ]; then
	APP_PATH=$CUR_PATH
else
  # CUR_PATH must be /usr/bin (the default installation path of this script)
  # or another sibling folder of "share" (in case of an alternative installation
  # folder like "/var/bin" where BiT must be installed into /var/share/backintime then)
	APP_PATH=$(readlink -m "${CUR_PATH}/../share/backintime/common")
fi

# -E ignores env vars like PYTHONPATH and PYTHONHOME that may modify
#    the behavior of the interpreter
# -s Don't add user site directory to sys.path
# TODO Should we use "$APP_PATH" (quoted) to prevent globbing and word splitting?
/usr/bin/python3 -Es $APP_PATH/backintime.py "$@"
