#!/bin/sh

#    Back In Time
#    Copyright (C) 2008-2009 Oprea Dan, Bart de Koning, Richard Bailey
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [ -f backintime.py ]; then
	APP_PATH="."
else
	APP_PATH="/usr/share/backintime/common"
fi

#starting a new ssh-agent all the time is just a workaround for
#https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/841672
#normally this should only be necessary if run as cronjob
#and the user is not logged in
ssh-agent python $APP_PATH/backintime.py "$@"

