# SPDX-FileCopyrightText: © 2023 Christian BUHTZ <c.buhtz@posteo.jp>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of the program "Back In Time" which is released under GNU
# General Public License v2 (GPLv2). See LICENSES directory or go to
# <https://spdx.org/licenses/GPL-2.0-or-later.html>.
#
# Generated at Sat Sep 19 19:19:16 2026 with help
# of package "babel" and "polib".
# https://babel.pocoo.org
# https://github.com/python-babel/babel
# pylint: disable=too-many-lines,missing-module-docstring
names = {
    'ar': {
        '_native': 'العربية',
        'pl': 'arabski',
        'lo': 'ອາຣັບ',
        'ja': 'アラビア語',
        'zh_TW': '阿拉伯文',
        'pt_BR': 'árabe',
        'pt': 'árabe',
        'eo': 'araba',
        'el': 'Αραβικά',
        'sl': 'arabščina',
        'uk': 'арабська',
        'ro': 'arabă',
        'ca': 'àrab',
        'ru': 'арабский',
        'bg': 'арабски',
        'eu': 'arabiera',
        'ar': 'العربية',
        'fa': 'عربی',
        'sr': 'арапски',
        'es': 'árabe',
        'fi': 'arabia',
        'de': 'Arabisch',
        'da': 'arabisk',
        'zh_CN': '阿拉伯语',
        'is': 'arabíska',
        'sr_RS@latin': 'арапски',
        'it': 'arabo',
        'ko': '아랍어',
        'hy': 'արաբերեն',
        'gl': 'árabe',
        'fr': 'arabe',
        'hu': 'arab',
        'nb': 'arabisk',
        'cs': 'arabština',
        'ka': 'არაბული',
        'sk': 'arabčina',
        'id': 'Arab',
        'nl': 'Arabisch',
        'tr': 'Arapça',
        'sv': 'arabiska',
        'he': 'ערבית',
        'lt': 'arabų',
        'et': 'araabia',
        'en': 'Arabic',
    },
    'bg': {
        '_native': 'български',
        'pl': 'bułgarski',
        'lo': 'ບັງກາຣຽນ',
        'ja': 'ブルガリア語',
        'zh_TW': '保加利亞文',
        'pt_BR': 'búlgaro',
        'pt': 'búlgaro',
        'eo': 'bulgara',
        'el': 'Βουλγαρικά',
        'sl': 'bolgarščina',
        'uk': 'болгарська',
        'ro': 'bulgară',
        'ca': 'búlgar',
        'ru': 'болгарский',
        'bg': 'български',
        'eu': 'bulgariera',
        'ar': 'البلغارية',
        'fa': 'بلغاری',
        'sr': 'бугарски',
        'es': 'búlgaro',
        'fi': 'bulgaria',
        'de': 'Bulgarisch',
        'da': 'bulgarsk',
        'zh_CN': '保加利亚语',
        'is': 'búlgarska',
        'sr_RS@latin': 'бугарски',
        'it': 'bulgaro',
        'ko': '불가리아어',
        'hy': 'բուլղարերեն',
        'gl': 'búlgaro',
        'fr': 'bulgare',
        'hu': 'bolgár',
        'nb': 'bulgarsk',
        'cs': 'bulharština',
        'ka': 'ბულგარული',
        'sk': 'bulharčina',
        'id': 'Bulgaria',
        'nl': 'Bulgaars',
        'tr': 'Bulgarca',
        'sv': 'bulgariska',
        'he': 'בולגרית',
        'lt': 'bulgarų',
        'et': 'bulgaaria',
        'en': 'Bulgarian',
    },
    'ca': {
        '_native': 'català',
        'pl': 'kataloński',
        'lo': 'ຄາຕາລານ',
        'ja': 'カタロニア語',
        'zh_TW': '加泰蘭文',
        'pt_BR': 'catalão',
        'pt': 'catalão',
        'eo': 'kataluna',
        'el': 'Καταλανικά',
        'sl': 'katalonščina',
        'uk': 'каталонська',
        'ro': 'catalană',
        'ca': 'català',
        'ru': 'каталанский',
        'bg': 'каталонски',
        'eu': 'katalana',
        'ar': 'الكتالانية',
        'fa': 'کاتالان',
        'sr': 'каталонски',
        'es': 'catalán',
        'fi': 'katalaani',
        'de': 'Katalanisch',
        'da': 'catalansk',
        'zh_CN': '加泰罗尼亚语',
        'is': 'katalónska',
        'sr_RS@latin': 'каталонски',
        'it': 'catalano',
        'ko': '카탈로니아어',
        'hy': 'կատալաներեն',
        'gl': 'catalán',
        'fr': 'catalan',
        'hu': 'katalán',
        'nb': 'katalansk',
        'cs': 'katalánština',
        'ka': 'კატალანური',
        'sk': 'katalánčina',
        'id': 'Katalan',
        'nl': 'Catalaans',
        'tr': 'Katalanca',
        'sv': 'katalanska',
        'he': 'קטלאנית',
        'lt': 'katalonų',
        'et': 'katalaani',
        'en': 'Catalan',
    },
    'cs': {
        '_native': 'čeština',
        'pl': 'czeski',
        'lo': 'ເຊກ',
        'ja': 'チェコ語',
        'zh_TW': '捷克文',
        'pt_BR': 'tcheco',
        'pt': 'tcheco',
        'eo': 'ĉeĥa',
        'el': 'Τσεχικά',
        'sl': 'češčina',
        'uk': 'чеська',
        'ro': 'cehă',
        'ca': 'txec',
        'ru': 'чешский',
        'bg': 'чешки',
        'eu': 'txekiera',
        'ar': 'التشيكية',
        'fa': 'چکی',
        'sr': 'чешки',
        'es': 'checo',
        'fi': 'tšekki',
        'de': 'Tschechisch',
        'da': 'tjekkisk',
        'zh_CN': '捷克语',
        'is': 'tékkneska',
        'sr_RS@latin': 'чешки',
        'it': 'ceco',
        'ko': '체코어',
        'hy': 'չեխերեն',
        'gl': 'checo',
        'fr': 'tchèque',
        'hu': 'cseh',
        'nb': 'tsjekkisk',
        'cs': 'čeština',
        'ka': 'ჩეხური',
        'sk': 'čeština',
        'id': 'Ceko',
        'nl': 'Tsjechisch',
        'tr': 'Çekçe',
        'sv': 'tjeckiska',
        'he': 'צ׳כית',
        'lt': 'čekų',
        'et': 'tšehhi',
        'en': 'Czech',
    },
    'da': {
        '_native': 'dansk',
        'pl': 'duński',
        'lo': 'ແດນິຊ',
        'ja': 'デンマーク語',
        'zh_TW': '丹麥文',
        'pt_BR': 'dinamarquês',
        'pt': 'dinamarquês',
        'eo': 'dana',
        'el': 'Δανικά',
        'sl': 'danščina',
        'uk': 'данська',
        'ro': 'daneză',
        'ca': 'danès',
        'ru': 'датский',
        'bg': 'датски',
        'eu': 'daniera',
        'ar': 'الدانمركية',
        'fa': 'دانمارکی',
        'sr': 'дански',
        'es': 'danés',
        'fi': 'tanska',
        'de': 'Dänisch',
        'da': 'dansk',
        'zh_CN': '丹麦语',
        'is': 'danska',
        'sr_RS@latin': 'дански',
        'it': 'danese',
        'ko': '덴마크어',
        'hy': 'դանիերեն',
        'gl': 'dinamarqués',
        'fr': 'danois',
        'hu': 'dán',
        'nb': 'dansk',
        'cs': 'dánština',
        'ka': 'დანიური',
        'sk': 'dánčina',
        'id': 'Dansk',
        'nl': 'Deens',
        'tr': 'Danca',
        'sv': 'danska',
        'he': 'דנית',
        'lt': 'danų',
        'et': 'taani',
        'en': 'Danish',
    },
    'de': {
        '_native': 'Deutsch',
        'pl': 'niemiecki',
        'lo': 'ເຢຍລະມັນ',
        'ja': 'ドイツ語',
        'zh_TW': '德文',
        'pt_BR': 'alemão',
        'pt': 'alemão',
        'eo': 'germana',
        'el': 'Γερμανικά',
        'sl': 'nemščina',
        'uk': 'німецька',
        'ro': 'germană',
        'ca': 'alemany',
        'ru': 'немецкий',
        'bg': 'немски',
        'eu': 'alemana',
        'ar': 'الألمانية',
        'fa': 'آلمانی',
        'sr': 'немачки',
        'es': 'alemán',
        'fi': 'saksa',
        'de': 'Deutsch',
        'da': 'tysk',
        'zh_CN': '德语',
        'is': 'þýska',
        'sr_RS@latin': 'немачки',
        'it': 'tedesco',
        'ko': '독일어',
        'hy': 'գերմաներեն',
        'gl': 'alemán',
        'fr': 'allemand',
        'hu': 'német',
        'nb': 'tysk',
        'cs': 'němčina',
        'ka': 'გერმანული',
        'sk': 'nemčina',
        'id': 'Jerman',
        'nl': 'Duits',
        'tr': 'Almanca',
        'sv': 'tyska',
        'he': 'גרמנית',
        'lt': 'vokiečių',
        'et': 'saksa',
        'en': 'German',
    },
    'el': {
        '_native': 'Ελληνικά',
        'pl': 'grecki',
        'lo': 'ກຣີກ',
        'ja': 'ギリシャ語',
        'zh_TW': '希臘文',
        'pt_BR': 'grego',
        'pt': 'grego',
        'eo': 'greka',
        'el': 'Ελληνικά',
        'sl': 'grščina',
        'uk': 'грецька',
        'ro': 'greacă',
        'ca': 'grec',
        'ru': 'греческий',
        'bg': 'гръцки',
        'eu': 'greziera',
        'ar': 'اليونانية',
        'fa': 'یونانی',
        'sr': 'грчки',
        'es': 'griego',
        'fi': 'kreikka',
        'de': 'Griechisch',
        'da': 'græsk',
        'zh_CN': '希腊语',
        'is': 'gríska',
        'sr_RS@latin': 'грчки',
        'it': 'greco',
        'ko': '그리스어',
        'hy': 'հունարեն',
        'gl': 'grego',
        'fr': 'grec',
        'hu': 'görög',
        'nb': 'gresk',
        'cs': 'řečtina',
        'ka': 'ბერძნული',
        'sk': 'gréčtina',
        'id': 'Yunani',
        'nl': 'Grieks',
        'tr': 'Yunanca',
        'sv': 'grekiska',
        'he': 'יוונית',
        'lt': 'graikų',
        'et': 'kreeka',
        'en': 'Greek',
    },
    'en': {
        '_native': 'English',
        'pl': 'angielski',
        'lo': 'ອັງກິດ',
        'ja': '英語',
        'zh_TW': '英文',
        'pt_BR': 'inglês',
        'pt': 'inglês',
        'eo': 'angla',
        'el': 'Αγγλικά',
        'sl': 'angleščina',
        'uk': 'англійська',
        'ro': 'engleză',
        'ca': 'anglès',
        'ru': 'английский',
        'bg': 'английски',
        'eu': 'ingelesa',
        'ar': 'الإنجليزية',
        'fa': 'انگلیسی',
        'sr': 'енглески',
        'es': 'inglés',
        'fi': 'englanti',
        'de': 'Englisch',
        'da': 'engelsk',
        'zh_CN': '英语',
        'is': 'enska',
        'sr_RS@latin': 'енглески',
        'it': 'inglese',
        'ko': '영어',
        'hy': 'անգլերեն',
        'gl': 'inglés',
        'fr': 'anglais',
        'hu': 'angol',
        'nb': 'engelsk',
        'cs': 'angličtina',
        'ka': 'ინგლისური',
        'sk': 'angličtina',
        'id': 'Inggris',
        'nl': 'Engels',
        'tr': 'İngilizce',
        'sv': 'engelska',
        'he': 'אנגלית',
        'lt': 'anglų',
        'et': 'inglise',
        'en': 'English',
    },
    'eo': {
        '_native': 'Esperanto',
        'pl': 'esperanto',
        'lo': 'ເອສປາຍ',
        'ja': 'エスペラント語',
        'zh_TW': '世界文',
        'pt_BR': 'esperanto',
        'pt': 'esperanto',
        'eo': 'Esperanto',
        'el': 'Εσπεράντο',
        'sl': 'esperanto',
        'uk': 'есперанто',
        'ro': 'esperanto',
        'ca': 'esperanto',
        'ru': 'эсперанто',
        'bg': 'есперанто',
        'eu': 'esperantoa',
        'ar': 'الإسبرانتو',
        'fa': 'اسپرانتو',
        'sr': 'есперанто',
        'es': 'esperanto',
        'fi': 'esperanto',
        'de': 'Esperanto',
        'da': 'esperanto',
        'zh_CN': '世界语',
        'is': 'esperantó',
        'sr_RS@latin': 'есперанто',
        'it': 'esperanto',
        'ko': '에스페란토어',
        'hy': 'էսպերանտո',
        'gl': 'esperanto',
        'fr': 'espéranto',
        'hu': 'eszperantó',
        'nb': 'esperanto',
        'cs': 'esperanto',
        'ka': 'ესპერანტო',
        'sk': 'esperanto',
        'id': 'Esperanto',
        'nl': 'Esperanto',
        'tr': 'Esperanto',
        'sv': 'esperanto',
        'he': 'אספרנטו',
        'lt': 'esperanto',
        'et': 'esperanto',
        'en': 'Esperanto',
    },
    'es': {
        '_native': 'español',
        'pl': 'hiszpański',
        'lo': 'ສະແປນນິຊ',
        'ja': 'スペイン語',
        'zh_TW': '西班牙文',
        'pt_BR': 'espanhol',
        'pt': 'espanhol',
        'eo': 'hispana',
        'el': 'Ισπανικά',
        'sl': 'španščina',
        'uk': 'іспанська',
        'ro': 'spaniolă',
        'ca': 'espanyol',
        'ru': 'испанский',
        'bg': 'испански',
        'eu': 'gaztelania',
        'ar': 'الإسبانية',
        'fa': 'اسپانیایی',
        'sr': 'шпански',
        'es': 'español',
        'fi': 'espanja',
        'de': 'Spanisch',
        'da': 'spansk',
        'zh_CN': '西班牙语',
        'is': 'spænska',
        'sr_RS@latin': 'шпански',
        'it': 'spagnolo',
        'ko': '스페인어',
        'hy': 'իսպաներեն',
        'gl': 'español',
        'fr': 'espagnol',
        'hu': 'spanyol',
        'nb': 'spansk',
        'cs': 'španělština',
        'ka': 'ესპანური',
        'sk': 'španielčina',
        'id': 'Spanyol',
        'nl': 'Spaans',
        'tr': 'İspanyolca',
        'sv': 'spanska',
        'he': 'ספרדית',
        'lt': 'ispanų',
        'et': 'hispaania',
        'en': 'Spanish',
    },
    'et': {
        '_native': 'eesti',
        'pl': 'estoński',
        'lo': 'ເອສໂຕນຽນ',
        'ja': 'エストニア語',
        'zh_TW': '愛沙尼亞文',
        'pt_BR': 'estoniano',
        'pt': 'estoniano',
        'eo': 'estona',
        'el': 'Εσθονικά',
        'sl': 'estonščina',
        'uk': 'естонська',
        'ro': 'estonă',
        'ca': 'estonià',
        'ru': 'эстонский',
        'bg': 'естонски',
        'eu': 'estoniera',
        'ar': 'الإستونية',
        'fa': 'استونیایی',
        'sr': 'естонски',
        'es': 'estonio',
        'fi': 'viro',
        'de': 'Estnisch',
        'da': 'estisk',
        'zh_CN': '爱沙尼亚语',
        'is': 'eistneska',
        'sr_RS@latin': 'естонски',
        'it': 'estone',
        'ko': '에스토니아어',
        'hy': 'էստոներեն',
        'gl': 'estoniano',
        'fr': 'estonien',
        'hu': 'észt',
        'nb': 'estisk',
        'cs': 'estonština',
        'ka': 'ესტონური',
        'sk': 'estónčina',
        'id': 'Estonia',
        'nl': 'Estisch',
        'tr': 'Estonca',
        'sv': 'estniska',
        'he': 'אסטונית',
        'lt': 'estų',
        'et': 'eesti',
        'en': 'Estonian',
    },
    'eu': {
        '_native': 'euskara',
        'pl': 'baskijski',
        'lo': 'ບັສກີ',
        'ja': 'バスク語',
        'zh_TW': '巴斯克文',
        'pt_BR': 'basco',
        'pt': 'basco',
        'eo': 'eŭska',
        'el': 'Βασκικά',
        'sl': 'baskovščina',
        'uk': 'баскська',
        'ro': 'bască',
        'ca': 'basc',
        'ru': 'баскский',
        'bg': 'баски',
        'eu': 'euskara',
        'ar': 'الباسكية',
        'fa': 'باسکی',
        'sr': 'баскијски',
        'es': 'euskera',
        'fi': 'baski',
        'de': 'Baskisch',
        'da': 'baskisk',
        'zh_CN': '巴斯克语',
        'is': 'baskneska',
        'sr_RS@latin': 'баскијски',
        'it': 'basco',
        'ko': '바스크어',
        'hy': 'բասկերեն',
        'gl': 'éuscaro',
        'fr': 'basque',
        'hu': 'baszk',
        'nb': 'baskisk',
        'cs': 'baskičtina',
        'ka': 'ბასკური',
        'sk': 'baskičtina',
        'id': 'Basque',
        'nl': 'Baskisch',
        'tr': 'Baskça',
        'sv': 'baskiska',
        'he': 'בסקית',
        'lt': 'baskų',
        'et': 'baski',
        'en': 'Basque',
    },
    'fa': {
        '_native': 'فارسی',
        'pl': 'perski',
        'lo': 'ເປີຊຽນ',
        'ja': 'ペルシア語',
        'zh_TW': '波斯文',
        'pt_BR': 'persa',
        'pt': 'persa',
        'eo': 'persa',
        'el': 'Περσικά',
        'sl': 'perzijščina',
        'uk': 'перська',
        'ro': 'persană',
        'ca': 'persa',
        'ru': 'персидский',
        'bg': 'персийски',
        'eu': 'persiera',
        'ar': 'الفارسية',
        'fa': 'فارسی',
        'sr': 'персијски',
        'es': 'persa',
        'fi': 'persia',
        'de': 'Persisch',
        'da': 'persisk',
        'zh_CN': '波斯语',
        'is': 'persneska',
        'sr_RS@latin': 'персијски',
        'it': 'persiano',
        'ko': '페르시아어',
        'hy': 'պարսկերեն',
        'gl': 'persa',
        'fr': 'persan',
        'hu': 'perzsa',
        'nb': 'persisk',
        'cs': 'perština',
        'ka': 'სპარსული',
        'sk': 'perzština',
        'id': 'Persia',
        'nl': 'Perzisch',
        'tr': 'Farsça',
        'sv': 'persiska',
        'he': 'פרסית',
        'lt': 'persų',
        'et': 'pärsia',
        'en': 'Persian',
    },
    'fi': {
        '_native': 'suomi',
        'pl': 'fiński',
        'lo': 'ຟິນນິຊ',
        'ja': 'フィンランド語',
        'zh_TW': '芬蘭文',
        'pt_BR': 'finlandês',
        'pt': 'finlandês',
        'eo': 'finna',
        'el': 'Φινλανδικά',
        'sl': 'finščina',
        'uk': 'фінська',
        'ro': 'finlandeză',
        'ca': 'finès',
        'ru': 'финский',
        'bg': 'фински',
        'eu': 'finlandiera',
        'ar': 'الفنلندية',
        'fa': 'فنلاندی',
        'sr': 'фински',
        'es': 'finés',
        'fi': 'suomi',
        'de': 'Finnisch',
        'da': 'finsk',
        'zh_CN': '芬兰语',
        'is': 'finnska',
        'sr_RS@latin': 'фински',
        'it': 'finlandese',
        'ko': '핀란드어',
        'hy': 'ֆիններեն',
        'gl': 'finés',
        'fr': 'finnois',
        'hu': 'finn',
        'nb': 'finsk',
        'cs': 'finština',
        'ka': 'ფინური',
        'sk': 'fínčina',
        'id': 'Suomi',
        'nl': 'Fins',
        'tr': 'Fince',
        'sv': 'finska',
        'he': 'פינית',
        'lt': 'suomių',
        'et': 'soome',
        'en': 'Finnish',
    },
    'fr': {
        '_native': 'français',
        'pl': 'francuski',
        'lo': 'ຝຣັ່ງ',
        'ja': 'フランス語',
        'zh_TW': '法文',
        'pt_BR': 'francês',
        'pt': 'francês',
        'eo': 'franca',
        'el': 'Γαλλικά',
        'sl': 'francoščina',
        'uk': 'французька',
        'ro': 'franceză',
        'ca': 'francès',
        'ru': 'французский',
        'bg': 'френски',
        'eu': 'frantsesa',
        'ar': 'الفرنسية',
        'fa': 'فرانسوی',
        'sr': 'француски',
        'es': 'francés',
        'fi': 'ranska',
        'de': 'Französisch',
        'da': 'fransk',
        'zh_CN': '法语',
        'is': 'franska',
        'sr_RS@latin': 'француски',
        'it': 'francese',
        'ko': '프랑스어',
        'hy': 'ֆրանսերեն',
        'gl': 'francés',
        'fr': 'français',
        'hu': 'francia',
        'nb': 'fransk',
        'cs': 'francouzština',
        'ka': 'ფრანგული',
        'sk': 'francúzština',
        'id': 'Prancis',
        'nl': 'Frans',
        'tr': 'Fransızca',
        'sv': 'franska',
        'he': 'צרפתית',
        'lt': 'prancūzų',
        'et': 'prantsuse',
        'en': 'French',
    },
    'gl': {
        '_native': 'galego',
        'pl': 'galicyjski',
        'lo': 'ກາລິຊຽນ',
        'ja': 'ガリシア語',
        'zh_TW': '加利西亞文',
        'pt_BR': 'galego',
        'pt': 'galego',
        'eo': 'galega',
        'el': 'Γαλικιανά',
        'sl': 'galicijščina',
        'uk': 'галісійська',
        'ro': 'galiciană',
        'ca': 'gallec',
        'ru': 'галисийский',
        'bg': 'галисийски',
        'eu': 'galiziera',
        'ar': 'الجاليكية',
        'fa': 'گالیسیایی',
        'sr': 'галицијски',
        'es': 'gallego',
        'fi': 'galicia',
        'de': 'Galicisch',
        'da': 'galicisk',
        'zh_CN': '加利西亚语',
        'is': 'galisíska',
        'sr_RS@latin': 'галицијски',
        'it': 'galiziano',
        'ko': '갈리시아어',
        'hy': 'գալիսերեն',
        'gl': 'galego',
        'fr': 'galicien',
        'hu': 'gallego',
        'nb': 'galisisk',
        'cs': 'galicijština',
        'ka': 'გალისიური',
        'sk': 'galícijčina',
        'id': 'Galisia',
        'nl': 'Galicisch',
        'tr': 'Galiçyaca',
        'sv': 'galiciska',
        'he': 'גליציאנית',
        'lt': 'galisų',
        'et': 'galeegi',
        'en': 'Galician',
    },
    'he': {
        '_native': 'עברית',
        'pl': 'hebrajski',
        'lo': 'ຮີບຣິວ',
        'ja': 'ヘブライ語',
        'zh_TW': '希伯來文',
        'pt_BR': 'hebraico',
        'pt': 'hebraico',
        'eo': 'hebrea',
        'el': 'Εβραϊκά',
        'sl': 'hebrejščina',
        'uk': 'іврит',
        'ro': 'ebraică',
        'ca': 'hebreu',
        'ru': 'иврит',
        'bg': 'иврит',
        'eu': 'hebreera',
        'ar': 'العبرية',
        'fa': 'عبری',
        'sr': 'хебрејски',
        'es': 'hebreo',
        'fi': 'heprea',
        'de': 'Hebräisch',
        'da': 'hebraisk',
        'zh_CN': '希伯来语',
        'is': 'hebreska',
        'sr_RS@latin': 'хебрејски',
        'it': 'ebraico',
        'ko': '히브리어',
        'hy': 'եբրայերեն',
        'gl': 'hebreo',
        'fr': 'hébreu',
        'hu': 'héber',
        'nb': 'hebraisk',
        'cs': 'hebrejština',
        'ka': 'ებრაული',
        'sk': 'hebrejčina',
        'id': 'Ibrani',
        'nl': 'Hebreeuws',
        'tr': 'İbranice',
        'sv': 'hebreiska',
        'he': 'עברית',
        'lt': 'hebrajų',
        'et': 'heebrea',
        'en': 'Hebrew',
    },
    'hu': {
        '_native': 'magyar',
        'pl': 'węgierski',
        'lo': 'ຮັງກາຣຽນ',
        'ja': 'ハンガリー語',
        'zh_TW': '匈牙利文',
        'pt_BR': 'húngaro',
        'pt': 'húngaro',
        'eo': 'hungara',
        'el': 'Ουγγρικά',
        'sl': 'madžarščina',
        'uk': 'угорська',
        'ro': 'maghiară',
        'ca': 'hongarès',
        'ru': 'венгерский',
        'bg': 'унгарски',
        'eu': 'hungariera',
        'ar': 'الهنغارية',
        'fa': 'مجاری',
        'sr': 'мађарски',
        'es': 'húngaro',
        'fi': 'unkari',
        'de': 'Ungarisch',
        'da': 'ungarsk',
        'zh_CN': '匈牙利语',
        'is': 'ungverska',
        'sr_RS@latin': 'мађарски',
        'it': 'ungherese',
        'ko': '헝가리어',
        'hy': 'հունգարերեն',
        'gl': 'húngaro',
        'fr': 'hongrois',
        'hu': 'magyar',
        'nb': 'ungarsk',
        'cs': 'maďarština',
        'ka': 'უნგრული',
        'sk': 'maďarčina',
        'id': 'Hungaria',
        'nl': 'Hongaars',
        'tr': 'Macarca',
        'sv': 'ungerska',
        'he': 'הונגרית',
        'lt': 'vengrų',
        'et': 'ungari',
        'en': 'Hungarian',
    },
    'hy': {
        '_native': 'հայերեն',
        'pl': 'ormiański',
        'lo': 'ອາເມນຽນ',
        'ja': 'アルメニア語',
        'zh_TW': '亞美尼亞文',
        'pt_BR': 'armênio',
        'pt': 'armênio',
        'eo': 'armena',
        'el': 'Αρμενικά',
        'sl': 'armenščina',
        'uk': 'вірменська',
        'ro': 'armeană',
        'ca': 'armeni',
        'ru': 'армянский',
        'bg': 'арменски',
        'eu': 'armeniera',
        'ar': 'الأرمنية',
        'fa': 'ارمنی',
        'sr': 'јерменски',
        'es': 'armenio',
        'fi': 'armenia',
        'de': 'Armenisch',
        'da': 'armensk',
        'zh_CN': '亚美尼亚语',
        'is': 'armenska',
        'sr_RS@latin': 'јерменски',
        'it': 'armeno',
        'ko': '아르메니아어',
        'hy': 'հայերեն',
        'gl': 'armenio',
        'fr': 'arménien',
        'hu': 'örmény',
        'nb': 'armensk',
        'cs': 'arménština',
        'ka': 'სომხური',
        'sk': 'arménčina',
        'id': 'Armenia',
        'nl': 'Armeens',
        'tr': 'Ermenice',
        'sv': 'armeniska',
        'he': 'ארמנית',
        'lt': 'armėnų',
        'et': 'armeenia',
        'en': 'Armenian',
    },
    'id': {
        '_native': 'Indonesia',
        'pl': 'indonezyjski',
        'lo': 'ອິນໂດເນຊຽນ',
        'ja': 'インドネシア語',
        'zh_TW': '印尼文',
        'pt_BR': 'indonésio',
        'pt': 'indonésio',
        'eo': 'indonezia',
        'el': 'Ινδονησιακά',
        'sl': 'indonezijščina',
        'uk': 'індонезійська',
        'ro': 'indoneziană',
        'ca': 'indonesi',
        'ru': 'индонезийский',
        'bg': 'индонезийски',
        'eu': 'indonesiera',
        'ar': 'الإندونيسية',
        'fa': 'اندونزیایی',
        'sr': 'индонежански',
        'es': 'indonesio',
        'fi': 'indonesia',
        'de': 'Indonesisch',
        'da': 'indonesisk',
        'zh_CN': '印度尼西亚语',
        'is': 'indónesíska',
        'sr_RS@latin': 'индонежански',
        'it': 'indonesiano',
        'ko': '인도네시아어',
        'hy': 'ինդոնեզերեն',
        'gl': 'indonesio',
        'fr': 'indonésien',
        'hu': 'indonéz',
        'nb': 'indonesisk',
        'cs': 'indonéština',
        'ka': 'ინდონეზიური',
        'sk': 'indonézština',
        'id': 'Indonesia',
        'nl': 'Indonesisch',
        'tr': 'Endonezce',
        'sv': 'indonesiska',
        'he': 'אינדונזית',
        'lt': 'indoneziečių',
        'et': 'indoneesia',
        'en': 'Indonesian',
    },
    'is': {
        '_native': 'íslenska',
        'pl': 'islandzki',
        'lo': 'ໄອສແລນດິກ',
        'ja': 'アイスランド語',
        'zh_TW': '冰島文',
        'pt_BR': 'islandês',
        'pt': 'islandês',
        'eo': 'islanda',
        'el': 'Ισλανδικά',
        'sl': 'islandščina',
        'uk': 'ісландська',
        'ro': 'islandeză',
        'ca': 'islandès',
        'ru': 'исландский',
        'bg': 'исландски',
        'eu': 'islandiera',
        'ar': 'الأيسلندية',
        'fa': 'ایسلندی',
        'sr': 'исландски',
        'es': 'islandés',
        'fi': 'islanti',
        'de': 'Isländisch',
        'da': 'islandsk',
        'zh_CN': '冰岛语',
        'is': 'íslenska',
        'sr_RS@latin': 'исландски',
        'it': 'islandese',
        'ko': '아이슬란드어',
        'hy': 'իսլանդերեն',
        'gl': 'islandés',
        'fr': 'islandais',
        'hu': 'izlandi',
        'nb': 'islandsk',
        'cs': 'islandština',
        'ka': 'ისლანდიური',
        'sk': 'islandčina',
        'id': 'Islandia',
        'nl': 'IJslands',
        'tr': 'İzlandaca',
        'sv': 'isländska',
        'he': 'איסלנדית',
        'lt': 'islandų',
        'et': 'islandi',
        'en': 'Icelandic',
    },
    'it': {
        '_native': 'italiano',
        'pl': 'włoski',
        'lo': 'ອິຕາລຽນ',
        'ja': 'イタリア語',
        'zh_TW': '義大利文',
        'pt_BR': 'italiano',
        'pt': 'italiano',
        'eo': 'itala',
        'el': 'Ιταλικά',
        'sl': 'italijanščina',
        'uk': 'італійська',
        'ro': 'italiană',
        'ca': 'italià',
        'ru': 'итальянский',
        'bg': 'италиански',
        'eu': 'italiera',
        'ar': 'الإيطالية',
        'fa': 'ایتالیایی',
        'sr': 'италијански',
        'es': 'italiano',
        'fi': 'italia',
        'de': 'Italienisch',
        'da': 'italiensk',
        'zh_CN': '意大利语',
        'is': 'ítalska',
        'sr_RS@latin': 'италијански',
        'it': 'italiano',
        'ko': '이탈리아어',
        'hy': 'իտալերեն',
        'gl': 'italiano',
        'fr': 'italien',
        'hu': 'olasz',
        'nb': 'italiensk',
        'cs': 'italština',
        'ka': 'იტალიური',
        'sk': 'taliančina',
        'id': 'Italia',
        'nl': 'Italiaans',
        'tr': 'İtalyanca',
        'sv': 'italienska',
        'he': 'איטלקית',
        'lt': 'italų',
        'et': 'itaalia',
        'en': 'Italian',
    },
    'ja': {
        '_native': '日本語',
        'pl': 'japoński',
        'lo': 'ຍີ່ປຸ່ນ',
        'ja': '日本語',
        'zh_TW': '日文',
        'pt_BR': 'japonês',
        'pt': 'japonês',
        'eo': 'japana',
        'el': 'Ιαπωνικά',
        'sl': 'japonščina',
        'uk': 'японська',
        'ro': 'japoneză',
        'ca': 'japonès',
        'ru': 'японский',
        'bg': 'японски',
        'eu': 'japoniera',
        'ar': 'اليابانية',
        'fa': 'ژاپنی',
        'sr': 'јапански',
        'es': 'japonés',
        'fi': 'japani',
        'de': 'Japanisch',
        'da': 'japansk',
        'zh_CN': '日语',
        'is': 'japanska',
        'sr_RS@latin': 'јапански',
        'it': 'giapponese',
        'ko': '일본어',
        'hy': 'ճապոներեն',
        'gl': 'xaponés',
        'fr': 'japonais',
        'hu': 'japán',
        'nb': 'japansk',
        'cs': 'japonština',
        'ka': 'იაპონური',
        'sk': 'japončina',
        'id': 'Jepang',
        'nl': 'Japans',
        'tr': 'Japonca',
        'sv': 'japanska',
        'he': 'יפנית',
        'lt': 'japonų',
        'et': 'jaapani',
        'en': 'Japanese',
    },
    'ka': {
        '_native': 'ქართული',
        'pl': 'gruziński',
        'lo': 'ຈໍຈຽນ',
        'ja': 'ジョージア語',
        'zh_TW': '喬治亞文',
        'pt_BR': 'georgiano',
        'pt': 'georgiano',
        'eo': 'kartvela',
        'el': 'Γεωργιανά',
        'sl': 'gruzijščina',
        'uk': 'грузинська',
        'ro': 'georgiană',
        'ca': 'georgià',
        'ru': 'грузинский',
        'bg': 'грузински',
        'eu': 'georgiera',
        'ar': 'الجورجية',
        'fa': 'گرجی',
        'sr': 'грузијски',
        'es': 'georgiano',
        'fi': 'georgia',
        'de': 'Georgisch',
        'da': 'georgisk',
        'zh_CN': '格鲁吉亚语',
        'is': 'georgíska',
        'sr_RS@latin': 'грузијски',
        'it': 'georgiano',
        'ko': '조지아어',
        'hy': 'վրացերեն',
        'gl': 'xeorxiano',
        'fr': 'géorgien',
        'hu': 'grúz',
        'nb': 'georgisk',
        'cs': 'gruzínština',
        'ka': 'ქართული',
        'sk': 'gruzínčina',
        'id': 'Georgia',
        'nl': 'Georgisch',
        'tr': 'Gürcüce',
        'sv': 'georgiska',
        'he': 'גאורגית',
        'lt': 'gruzinų',
        'et': 'gruusia',
        'en': 'Georgian',
    },
    'ko': {
        '_native': '한국어',
        'pl': 'koreański',
        'lo': 'ເກົາຫລີ',
        'ja': '韓国語',
        'zh_TW': '韓文',
        'pt_BR': 'coreano',
        'pt': 'coreano',
        'eo': 'korea',
        'el': 'Κορεατικά',
        'sl': 'korejščina',
        'uk': 'корейська',
        'ro': 'coreeană',
        'ca': 'coreà',
        'ru': 'корейский',
        'bg': 'корейски',
        'eu': 'koreera',
        'ar': 'الكورية',
        'fa': 'کره‌ای',
        'sr': 'корејски',
        'es': 'coreano',
        'fi': 'korea',
        'de': 'Koreanisch',
        'da': 'koreansk',
        'zh_CN': '韩语',
        'is': 'kóreska',
        'sr_RS@latin': 'корејски',
        'it': 'coreano',
        'ko': '한국어',
        'hy': 'կորեերեն',
        'gl': 'coreano',
        'fr': 'coréen',
        'hu': 'koreai',
        'nb': 'koreansk',
        'cs': 'korejština',
        'ka': 'კორეული',
        'sk': 'kórejčina',
        'id': 'Korea',
        'nl': 'Koreaans',
        'tr': 'Korece',
        'sv': 'koreanska',
        'he': 'קוריאנית',
        'lt': 'korėjiečių',
        'et': 'korea',
        'en': 'Korean',
    },
    'lo': {
        '_native': 'ລາວ',
        'pl': 'laotański',
        'lo': 'ລາວ',
        'ja': 'ラオ語',
        'zh_TW': '寮文',
        'pt_BR': 'laosiano',
        'pt': 'laosiano',
        'eo': 'laŭa',
        'el': 'Λαοτινά',
        'sl': 'laoščina',
        'uk': 'лаоська',
        'ro': 'laoțiană',
        'ca': 'laosià',
        'ru': 'лаосский',
        'bg': 'лаоски',
        'eu': 'laosera',
        'ar': 'اللاوية',
        'fa': 'لائوسی',
        'sr': 'лаоски',
        'es': 'lao',
        'fi': 'lao',
        'de': 'Laotisch',
        'da': 'lao',
        'zh_CN': '老挝语',
        'is': 'laó',
        'sr_RS@latin': 'лаоски',
        'it': 'lao',
        'ko': '라오어',
        'hy': 'լաոսերեն',
        'gl': 'laosiano',
        'fr': 'lao',
        'hu': 'lao',
        'nb': 'laotisk',
        'cs': 'laoština',
        'ka': 'ლაოსური',
        'sk': 'laoština',
        'id': 'Lao',
        'nl': 'Laotiaans',
        'tr': 'Lao dili',
        'sv': 'laotiska',
        'he': 'לאו',
        'lt': 'laosiečių',
        'et': 'lao',
        'en': 'Lao',
    },
    'lt': {
        '_native': 'lietuvių',
        'pl': 'litewski',
        'lo': 'ລິທົວນຽນ',
        'ja': 'リトアニア語',
        'zh_TW': '立陶宛文',
        'pt_BR': 'lituano',
        'pt': 'lituano',
        'eo': 'litova',
        'el': 'Λιθουανικά',
        'sl': 'litovščina',
        'uk': 'литовська',
        'ro': 'lituaniană',
        'ca': 'lituà',
        'ru': 'литовский',
        'bg': 'литовски',
        'eu': 'lituaniera',
        'ar': 'الليتوانية',
        'fa': 'لیتوانیایی',
        'sr': 'литвански',
        'es': 'lituano',
        'fi': 'liettua',
        'de': 'Litauisch',
        'da': 'litauisk',
        'zh_CN': '立陶宛语',
        'is': 'litháíska',
        'sr_RS@latin': 'литвански',
        'it': 'lituano',
        'ko': '리투아니아어',
        'hy': 'լիտվերեն',
        'gl': 'lituano',
        'fr': 'lituanien',
        'hu': 'litván',
        'nb': 'litauisk',
        'cs': 'litevština',
        'ka': 'ლიეტუვური',
        'sk': 'litovčina',
        'id': 'Lituania',
        'nl': 'Litouws',
        'tr': 'Litvanca',
        'sv': 'litauiska',
        'he': 'ליטאית',
        'lt': 'lietuvių',
        'et': 'leedu',
        'en': 'Lithuanian',
    },
    'nb': {
        '_native': 'norsk bokmål',
        'pl': 'norweski (bokmål)',
        'lo': 'ນໍເວຈຽນ ບັອກມອລ',
        'ja': 'ノルウェー語(ブークモール)',
        'zh_TW': '書面挪威文',
        'pt_BR': 'bokmål norueguês',
        'pt': 'bokmål norueguês',
        'eo': 'dannorvega',
        'el': 'Νορβηγικά Μποκμάλ',
        'sl': 'knjižna norveščina',
        'uk': 'норвезька (букмол)',
        'ro': 'norvegiană bokmål',
        'ca': 'noruec bokmål',
        'ru': 'норвежский букмол',
        'bg': 'норвежки (букмол)',
        'eu': 'bokmål (norvegiera)',
        'ar': 'النرويجية بوكمال',
        'fa': 'نروژی بوک‌مُل',
        'sr': 'норвешки букмол',
        'es': 'noruego bokmal',
        'fi': 'norjan bokmål',
        'de': 'Norwegisch (Bokmål)',
        'da': 'bokmål',
        'zh_CN': '书面挪威语',
        'is': 'norskt bókmál',
        'sr_RS@latin': 'норвешки букмол',
        'it': 'norvegese bokmål',
        'ko': '노르웨이어(보크말)',
        'hy': 'գրքային նորվեգերեն',
        'gl': 'noruegués bokmål',
        'fr': 'norvégien bokmål',
        'hu': 'norvég (bokmål)',
        'nb': 'norsk bokmål',
        'cs': 'norština (bokmål)',
        'ka': 'ნორვეგიული ბუკმოლი',
        'sk': 'nórčina (bokmal)',
        'id': 'Bokmål Norwegia',
        'nl': 'Noors - Bokmål',
        'tr': 'Norveççe Bokmål',
        'sv': 'norskt bokmål',
        'he': 'נורווגית ספרותית',
        'lt': 'norvegų bukmolas',
        'et': 'norra bokmål',
        'en': 'Norwegian Bokmål',
    },
    'nl': {
        '_native': 'Nederlands',
        'pl': 'niderlandzki',
        'lo': 'ດັຊ',
        'ja': 'オランダ語',
        'zh_TW': '荷蘭文',
        'pt_BR': 'holandês',
        'pt': 'holandês',
        'eo': 'nederlanda',
        'el': 'Ολλανδικά',
        'sl': 'nizozemščina',
        'uk': 'нідерландська',
        'ro': 'neerlandeză',
        'ca': 'neerlandès',
        'ru': 'нидерландский',
        'bg': 'нидерландски',
        'eu': 'nederlandera',
        'ar': 'الهولندية',
        'fa': 'هلندی',
        'sr': 'холандски',
        'es': 'neerlandés',
        'fi': 'hollanti',
        'de': 'Niederländisch',
        'da': 'nederlandsk',
        'zh_CN': '荷兰语',
        'is': 'hollenska',
        'sr_RS@latin': 'холандски',
        'it': 'olandese',
        'ko': '네덜란드어',
        'hy': 'հոլանդերեն',
        'gl': 'neerlandés',
        'fr': 'néerlandais',
        'hu': 'holland',
        'nb': 'nederlandsk',
        'cs': 'nizozemština',
        'ka': 'ნიდერლანდური',
        'sk': 'holandčina',
        'id': 'Belanda',
        'nl': 'Nederlands',
        'tr': 'Felemenkçe',
        'sv': 'nederländska',
        'he': 'הולנדית',
        'lt': 'olandų',
        'et': 'hollandi',
        'en': 'Dutch',
    },
    'pl': {
        '_native': 'polski',
        'pl': 'polski',
        'lo': 'ໂປລິຊ',
        'ja': 'ポーランド語',
        'zh_TW': '波蘭文',
        'pt_BR': 'polonês',
        'pt': 'polonês',
        'eo': 'pola',
        'el': 'Πολωνικά',
        'sl': 'poljščina',
        'uk': 'польська',
        'ro': 'poloneză',
        'ca': 'polonès',
        'ru': 'польский',
        'bg': 'полски',
        'eu': 'poloniera',
        'ar': 'البولندية',
        'fa': 'لهستانی',
        'sr': 'пољски',
        'es': 'polaco',
        'fi': 'puola',
        'de': 'Polnisch',
        'da': 'polsk',
        'zh_CN': '波兰语',
        'is': 'pólska',
        'sr_RS@latin': 'пољски',
        'it': 'polacco',
        'ko': '폴란드어',
        'hy': 'լեհերեն',
        'gl': 'polaco',
        'fr': 'polonais',
        'hu': 'lengyel',
        'nb': 'polsk',
        'cs': 'polština',
        'ka': 'პოლონური',
        'sk': 'poľština',
        'id': 'Polski',
        'nl': 'Pools',
        'tr': 'Lehçe',
        'sv': 'polska',
        'he': 'פולנית',
        'lt': 'lenkų',
        'et': 'poola',
        'en': 'Polish',
    },
    'pt': {
        '_native': 'português',
        'pl': 'portugalski',
        'lo': 'ປອກຕຸຍກິສ',
        'ja': 'ポルトガル語',
        'zh_TW': '葡萄牙文',
        'pt_BR': 'português',
        'pt': 'português',
        'eo': 'portugala',
        'el': 'Πορτογαλικά',
        'sl': 'portugalščina',
        'uk': 'португальська',
        'ro': 'portugheză',
        'ca': 'portuguès',
        'ru': 'португальский',
        'bg': 'португалски',
        'eu': 'portugesa',
        'ar': 'البرتغالية',
        'fa': 'پرتغالی',
        'sr': 'португалски',
        'es': 'portugués',
        'fi': 'portugali',
        'de': 'Portugiesisch',
        'da': 'portugisisk',
        'zh_CN': '葡萄牙语',
        'is': 'portúgalska',
        'sr_RS@latin': 'португалски',
        'it': 'portoghese',
        'ko': '포르투갈어',
        'hy': 'պորտուգալերեն',
        'gl': 'portugués',
        'fr': 'portugais',
        'hu': 'portugál',
        'nb': 'portugisisk',
        'cs': 'portugalština',
        'ka': 'პორტუგალიური',
        'sk': 'portugalčina',
        'id': 'Portugis',
        'nl': 'Portugees',
        'tr': 'Portekizce',
        'sv': 'portugisiska',
        'he': 'פורטוגזית',
        'lt': 'portugalų',
        'et': 'portugali',
        'en': 'Portuguese',
    },
    'pt_BR': {
        '_native': 'português (Brasil)',
        'pl': 'portugalski (Brazylia)',
        'lo': 'ປອກຕຸຍກິສ (ບຣາຊິວ)',
        'ja': 'ポルトガル語 (ブラジル)',
        'zh_TW': '葡萄牙文 (巴西)',
        'pt_BR': 'português (Brasil)',
        'pt': 'português (Brasil)',
        'eo': 'portugala (Brazilo)',
        'el': 'Πορτογαλικά (Βραζιλία)',
        'sl': 'portugalščina (Brazilija)',
        'uk': 'португальська (Бразилія)',
        'ro': 'portugheză (Brazilia)',
        'ca': 'portuguès (Brasil)',
        'ru': 'португальский (Бразилия)',
        'bg': 'португалски (Бразилия)',
        'eu': 'portugesa (Brasil)',
        'ar': 'البرتغالية (البرازيل)',
        'fa': 'پرتغالی (برزیل)',
        'sr': 'португалски (Бразил)',
        'es': 'portugués (Brasil)',
        'fi': 'portugali (Brasilia)',
        'de': 'Portugiesisch (Brasilien)',
        'da': 'portugisisk (Brasilien)',
        'zh_CN': '葡萄牙语 (巴西)',
        'is': 'portúgalska (Brasilía)',
        'sr_RS@latin': 'португалски (Бразил)',
        'it': 'portoghese (Brasile)',
        'ko': '포르투갈어 (브라질)',
        'hy': 'պորտուգալերեն (Բրազիլիա)',
        'gl': 'portugués (Brasil)',
        'fr': 'portugais (Brésil)',
        'hu': 'portugál (Brazília)',
        'nb': 'portugisisk (Brasil)',
        'cs': 'portugalština (Brazílie)',
        'ka': 'პორტუგალიური (ბრაზილია)',
        'sk': 'portugalčina (Brazília)',
        'id': 'Portugis (Brasil)',
        'nl': 'Portugees (Brazilië)',
        'tr': 'Portekizce (Brezilya)',
        'sv': 'portugisiska (Brasilien)',
        'he': 'פורטוגזית (ברזיל)',
        'lt': 'portugalų (Brazilija)',
        'et': 'portugali (Brasiilia)',
        'en': 'Portuguese (Brazil)',
    },
    'ro': {
        '_native': 'română',
        'pl': 'rumuński',
        'lo': 'ໂຣແມນຽນ',
        'ja': 'ルーマニア語',
        'zh_TW': '羅馬尼亞文',
        'pt_BR': 'romeno',
        'pt': 'romeno',
        'eo': 'rumana',
        'el': 'Ρουμανικά',
        'sl': 'romunščina',
        'uk': 'румунська',
        'ro': 'română',
        'ca': 'romanès',
        'ru': 'румынский',
        'bg': 'румънски',
        'eu': 'errumaniera',
        'ar': 'الرومانية',
        'fa': 'رومانیایی',
        'sr': 'румунски',
        'es': 'rumano',
        'fi': 'romania',
        'de': 'Rumänisch',
        'da': 'rumænsk',
        'zh_CN': '罗马尼亚语',
        'is': 'rúmenska',
        'sr_RS@latin': 'румунски',
        'it': 'rumeno',
        'ko': '루마니아어',
        'hy': 'ռումիներեն',
        'gl': 'romanés',
        'fr': 'roumain',
        'hu': 'román',
        'nb': 'rumensk',
        'cs': 'rumunština',
        'ka': 'რუმინული',
        'sk': 'rumunčina',
        'id': 'Rumania',
        'nl': 'Roemeens',
        'tr': 'Rumence',
        'sv': 'rumänska',
        'he': 'רומנית',
        'lt': 'rumunų',
        'et': 'rumeenia',
        'en': 'Romanian',
    },
    'ru': {
        '_native': 'русский',
        'pl': 'rosyjski',
        'lo': 'ລັດເຊຍ',
        'ja': 'ロシア語',
        'zh_TW': '俄文',
        'pt_BR': 'russo',
        'pt': 'russo',
        'eo': 'rusa',
        'el': 'Ρωσικά',
        'sl': 'ruščina',
        'uk': 'російська',
        'ro': 'rusă',
        'ca': 'rus',
        'ru': 'русский',
        'bg': 'руски',
        'eu': 'errusiera',
        'ar': 'الروسية',
        'fa': 'روسی',
        'sr': 'руски',
        'es': 'ruso',
        'fi': 'venäjä',
        'de': 'Russisch',
        'da': 'russisk',
        'zh_CN': '俄语',
        'is': 'rússneska',
        'sr_RS@latin': 'руски',
        'it': 'russo',
        'ko': '러시아어',
        'hy': 'ռուսերեն',
        'gl': 'ruso',
        'fr': 'russe',
        'hu': 'orosz',
        'nb': 'russisk',
        'cs': 'ruština',
        'ka': 'რუსული',
        'sk': 'ruština',
        'id': 'Rusia',
        'nl': 'Russisch',
        'tr': 'Rusça',
        'sv': 'ryska',
        'he': 'רוסית',
        'lt': 'rusų',
        'et': 'vene',
        'en': 'Russian',
    },
    'sk': {
        '_native': 'slovenčina',
        'pl': 'słowacki',
        'lo': 'ສະໂລແວັກ',
        'ja': 'スロバキア語',
        'zh_TW': '斯洛伐克文',
        'pt_BR': 'eslovaco',
        'pt': 'eslovaco',
        'eo': 'slovaka',
        'el': 'Σλοβακικά',
        'sl': 'slovaščina',
        'uk': 'словацька',
        'ro': 'slovacă',
        'ca': 'eslovac',
        'ru': 'словацкий',
        'bg': 'словашки',
        'eu': 'eslovakiera',
        'ar': 'السلوفاكية',
        'fa': 'اسلواکی',
        'sr': 'словачки',
        'es': 'eslovaco',
        'fi': 'slovakki',
        'de': 'Slowakisch',
        'da': 'slovakisk',
        'zh_CN': '斯洛伐克语',
        'is': 'slóvakíska',
        'sr_RS@latin': 'словачки',
        'it': 'slovacco',
        'ko': '슬로바키아어',
        'hy': 'սլովակերեն',
        'gl': 'eslovaco',
        'fr': 'slovaque',
        'hu': 'szlovák',
        'nb': 'slovakisk',
        'cs': 'slovenština',
        'ka': 'სლოვაკური',
        'sk': 'slovenčina',
        'id': 'Slovak',
        'nl': 'Slowaaks',
        'tr': 'Slovakça',
        'sv': 'slovakiska',
        'he': 'סלובקית',
        'lt': 'slovakų',
        'et': 'slovaki',
        'en': 'Slovak',
    },
    'sl': {
        '_native': 'slovenščina',
        'pl': 'słoweński',
        'lo': 'ສະໂລເວນຽນ',
        'ja': 'スロベニア語',
        'zh_TW': '斯洛維尼亞文',
        'pt_BR': 'esloveno',
        'pt': 'esloveno',
        'eo': 'slovena',
        'el': 'Σλοβενικά',
        'sl': 'slovenščina',
        'uk': 'словенська',
        'ro': 'slovenă',
        'ca': 'eslovè',
        'ru': 'словенский',
        'bg': 'словенски',
        'eu': 'esloveniera',
        'ar': 'السلوفانية',
        'fa': 'اسلوونیایی',
        'sr': 'словеначки',
        'es': 'esloveno',
        'fi': 'sloveeni',
        'de': 'Slowenisch',
        'da': 'slovensk',
        'zh_CN': '斯洛文尼亚语',
        'is': 'slóvenska',
        'sr_RS@latin': 'словеначки',
        'it': 'sloveno',
        'ko': '슬로베니아어',
        'hy': 'սլովեներեն',
        'gl': 'esloveno',
        'fr': 'slovène',
        'hu': 'szlovén',
        'nb': 'slovensk',
        'cs': 'slovinština',
        'ka': 'სლოვენური',
        'sk': 'slovinčina',
        'id': 'Slovenia',
        'nl': 'Sloveens',
        'tr': 'Slovence',
        'sv': 'slovenska',
        'he': 'סלובנית',
        'lt': 'slovėnų',
        'et': 'sloveeni',
        'en': 'Slovenian',
    },
    'sr': {
        '_native': 'српски',
        'pl': 'serbski',
        'lo': 'ເຊີບຽນ',
        'ja': 'セルビア語',
        'zh_TW': '塞爾維亞文',
        'pt_BR': 'sérvio',
        'pt': 'sérvio',
        'eo': 'serba',
        'el': 'Σερβικά',
        'sl': 'srbščina',
        'uk': 'сербська',
        'ro': 'sârbă',
        'ca': 'serbi',
        'ru': 'сербский',
        'bg': 'сръбски',
        'eu': 'serbiera',
        'ar': 'الصربية',
        'fa': 'صربی',
        'sr': 'српски',
        'es': 'serbio',
        'fi': 'serbia',
        'de': 'Serbisch',
        'da': 'serbisk',
        'zh_CN': '塞尔维亚语',
        'is': 'serbneska',
        'sr_RS@latin': 'српски',
        'it': 'serbo',
        'ko': '세르비아어',
        'hy': 'սերբերեն',
        'gl': 'serbio',
        'fr': 'serbe',
        'hu': 'szerb',
        'nb': 'serbisk',
        'cs': 'srbština',
        'ka': 'სერბული',
        'sk': 'srbčina',
        'id': 'Serbia',
        'nl': 'Servisch',
        'tr': 'Sırpça',
        'sv': 'serbiska',
        'he': 'סרבית',
        'lt': 'serbų',
        'et': 'serbia',
        'en': 'Serbian',
    },
    'sr_RS@latin': {
        '_native': 'српски (ћирилица, Србија)',
        'pl': 'serbski (cyrylica, Serbia)',
        'lo': 'ເຊີບຽນ (ຊີຣິວລິກ, ເຊີເບຍ)',
        'ja': 'セルビア語 (キリル文字, セルビア)',
        'zh_TW': '塞爾維亞文 (西里爾文字, 塞爾維亞)',
        'pt_BR': 'sérvio (cirílico, Sérvia)',
        'pt': 'sérvio (cirílico, Sérvia)',
        'eo': 'serba (cirila, Serbujo)',
        'el': 'Σερβικά (Κυριλλικό, Σερβία)',
        'sl': 'srbščina (cirilica, Srbija)',
        'uk': 'сербська (кирилиця, Сербія)',
        'ro': 'sârbă (chirilică, Serbia)',
        'ca': 'serbi (ciríl·lic, Sèrbia)',
        'ru': 'сербский (кириллица, Сербия)',
        'bg': 'сръбски (кирилица, Сърбия)',
        'eu': 'serbiera (zirilikoa, Serbia)',
        'ar': 'الصربية (السيريلية, صربيا)',
        'fa': 'صربی (سیریلی, صربستان)',
        'sr': 'српски (ћирилица, Србија)',
        'es': 'serbio (cirílico, Serbia)',
        'fi': 'serbia (kyrillinen, Serbia)',
        'de': 'Serbisch (Kyrillisch, Serbien)',
        'da': 'serbisk (kyrillisk, Serbien)',
        'zh_CN': '塞尔维亚语 (西里尔文, 塞尔维亚)',
        'is': 'serbneska (kyrillískt, Serbía)',
        'sr_RS@latin': 'српски (ћирилица, Србија)',
        'it': 'serbo (cirillico, Serbia)',
        'ko': '세르비아어 (키릴 문자, 세르비아)',
        'hy': 'սերբերեն (կյուրեղագիր, Սերբիա)',
        'gl': 'serbio (cirílico, Serbia)',
        'fr': 'serbe (cyrillique, Serbie)',
        'hu': 'szerb (Cirill, Szerbia)',
        'nb': 'serbisk (kyrillisk, Serbia)',
        'cs': 'srbština (cyrilice, Srbsko)',
        'ka': 'სერბული (კირილიცა, სერბეთი)',
        'sk': 'srbčina (cyrilika, Srbsko)',
        'id': 'Serbia (Sirilik, Serbia)',
        'nl': 'Servisch (Cyrillisch, Servië)',
        'tr': 'Sırpça (Kiril, Sırbistan)',
        'sv': 'serbiska (kyrilliska, Serbien)',
        'he': 'סרבית (קירילי, סרביה)',
        'lt': 'serbų (kirilica, Serbija)',
        'et': 'serbia (kirillitsa, Serbia)',
        'en': 'Serbian (Cyrillic, Serbia)',
    },
    'sv': {
        '_native': 'svenska',
        'pl': 'szwedzki',
        'lo': 'ສະວີດິຊ',
        'ja': 'スウェーデン語',
        'zh_TW': '瑞典文',
        'pt_BR': 'sueco',
        'pt': 'sueco',
        'eo': 'sveda',
        'el': 'Σουηδικά',
        'sl': 'švedščina',
        'uk': 'шведська',
        'ro': 'suedeză',
        'ca': 'suec',
        'ru': 'шведский',
        'bg': 'шведски',
        'eu': 'suediera',
        'ar': 'السويدية',
        'fa': 'سوئدی',
        'sr': 'шведски',
        'es': 'sueco',
        'fi': 'ruotsi',
        'de': 'Schwedisch',
        'da': 'svensk',
        'zh_CN': '瑞典语',
        'is': 'sænska',
        'sr_RS@latin': 'шведски',
        'it': 'svedese',
        'ko': '스웨덴어',
        'hy': 'շվեդերեն',
        'gl': 'sueco',
        'fr': 'suédois',
        'hu': 'svéd',
        'nb': 'svensk',
        'cs': 'švédština',
        'ka': 'შვედური',
        'sk': 'švédčina',
        'id': 'Swedia',
        'nl': 'Zweeds',
        'tr': 'İsveççe',
        'sv': 'svenska',
        'he': 'שוודית',
        'lt': 'švedų',
        'et': 'rootsi',
        'en': 'Swedish',
    },
    'tr': {
        '_native': 'Türkçe',
        'pl': 'turecki',
        'lo': 'ເທີຄິຊ',
        'ja': 'トルコ語',
        'zh_TW': '土耳其文',
        'pt_BR': 'turco',
        'pt': 'turco',
        'eo': 'turka',
        'el': 'Τουρκικά',
        'sl': 'turščina',
        'uk': 'турецька',
        'ro': 'turcă',
        'ca': 'turc',
        'ru': 'турецкий',
        'bg': 'турски',
        'eu': 'turkiera',
        'ar': 'التركية',
        'fa': 'ترکی استانبولی',
        'sr': 'турски',
        'es': 'turco',
        'fi': 'turkki',
        'de': 'Türkisch',
        'da': 'tyrkisk',
        'zh_CN': '土耳其语',
        'is': 'tyrkneska',
        'sr_RS@latin': 'турски',
        'it': 'turco',
        'ko': '튀르키예어',
        'hy': 'թուրքերեն',
        'gl': 'turco',
        'fr': 'turc',
        'hu': 'török',
        'nb': 'tyrkisk',
        'cs': 'turečtina',
        'ka': 'თურქული',
        'sk': 'turečtina',
        'id': 'Turki',
        'nl': 'Turks',
        'tr': 'Türkçe',
        'sv': 'turkiska',
        'he': 'טורקית',
        'lt': 'turkų',
        'et': 'türgi',
        'en': 'Turkish',
    },
    'uk': {
        '_native': 'українська',
        'pl': 'ukraiński',
        'lo': 'ຢູເຄຣນຽນ',
        'ja': 'ウクライナ語',
        'zh_TW': '烏克蘭文',
        'pt_BR': 'ucraniano',
        'pt': 'ucraniano',
        'eo': 'ukraina',
        'el': 'Ουκρανικά',
        'sl': 'ukrajinščina',
        'uk': 'українська',
        'ro': 'ucraineană',
        'ca': 'ucraïnès',
        'ru': 'украинский',
        'bg': 'украински',
        'eu': 'ukrainera',
        'ar': 'الأوكرانية',
        'fa': 'اوکراینی',
        'sr': 'украјински',
        'es': 'ucraniano',
        'fi': 'ukraina',
        'de': 'Ukrainisch',
        'da': 'ukrainsk',
        'zh_CN': '乌克兰语',
        'is': 'úkraínska',
        'sr_RS@latin': 'украјински',
        'it': 'ucraino',
        'ko': '우크라이나어',
        'hy': 'ուկրաիներեն',
        'gl': 'ucraíno',
        'fr': 'ukrainien',
        'hu': 'ukrán',
        'nb': 'ukrainsk',
        'cs': 'ukrajinština',
        'ka': 'უკრაინული',
        'sk': 'ukrajinčina',
        'id': 'Ukraina',
        'nl': 'Oekraïens',
        'tr': 'Ukraynaca',
        'sv': 'ukrainska',
        'he': 'אוקראינית',
        'lt': 'ukrainiečių',
        'et': 'ukraina',
        'en': 'Ukrainian',
    },
    'zh_CN': {
        '_native': '中文 (简体, 中国)',
        'pl': 'chiński (uproszczone, Chiny)',
        'lo': 'ຈີນ (ແບບຮຽບງ່າຍ, ຈີນ)',
        'ja': '中国語 (簡体字, 中国)',
        'zh_TW': '中文 (簡體, 中國)',
        'pt_BR': 'chinês (simplificado, China)',
        'pt': 'chinês (simplificado, China)',
        'eo': 'ĉina (simpligita, Ĉinujo)',
        'el': 'Κινεζικά (Απλοποιημένο, Κίνα)',
        'sl': 'kitajščina (poenostavljena pisava, Kitajska)',
        'uk': 'китайська (спрощена, Китай)',
        'ro': 'chineză (simplificată, China)',
        'ca': 'xinès (simplificat, Xina)',
        'ru': 'китайский (упрощенная, Китай)',
        'bg': 'китайски (опростена, Китай)',
        'eu': 'txinera (sinplifikatua, Txina)',
        'ar': 'الصينية (المبسطة, الصين)',
        'fa': 'چینی (ساده‌شده, چین)',
        'sr': 'кинески (поједностављено кинеско писмо, Кина)',
        'es': 'chino (simplificado, China)',
        'fi': 'kiina (yksinkertaistettu, Kiina)',
        'de': 'Chinesisch (Vereinfacht, China)',
        'da': 'kinesisk (forenklet, Kina)',
        'zh_CN': '中文 (简体, 中国)',
        'is': 'kínverska (einfaldað, Kína)',
        'sr_RS@latin': 'кинески (поједностављено кинеско писмо, Кина)',
        'it': 'cinese (semplificato, Cina)',
        'ko': '중국어 (간체, 중국)',
        'hy': 'չինարեն (պարզեցված, Չինաստան)',
        'gl': 'chinés (simplificado, China)',
        'fr': 'chinois (simplifié, Chine)',
        'hu': 'kínai (Egyszerűsített, Kína)',
        'nb': 'kinesisk (forenklet, Kina)',
        'cs': 'čínština (zjednodušené, Čína)',
        'ka': 'ჩინური (გამარტივებული, ჩინეთი)',
        'sk': 'čínština (zjednodušené, Čína)',
        'id': 'Tionghoa (Sederhana, Tiongkok)',
        'nl': 'Chinees (vereenvoudigd, China)',
        'tr': 'Çince (Basitleştirilmiş, Çin)',
        'sv': 'kinesiska (förenklad, Kina)',
        'he': 'סינית (פשוט, סין)',
        'lt': 'kinų (supaprastinti, Kinija)',
        'et': 'hiina (lihtsustatud, Hiina)',
        'en': 'Chinese (Simplified, China)',
    },
    'zh_TW': {
        '_native': '中文 (繁體, 台灣)',
        'pl': 'chiński (tradycyjne, Tajwan)',
        'lo': 'ຈີນ (ແບບດັ້ງເດີມ, ໄຕ້ຫວັນ)',
        'ja': '中国語 (繁体字, 台湾)',
        'zh_TW': '中文 (繁體, 台灣)',
        'pt_BR': 'chinês (tradicional, Taiwan)',
        'pt': 'chinês (tradicional, Taiwan)',
        'eo': 'ĉina (tradicia, Tajvano)',
        'el': 'Κινεζικά (Παραδοσιακό, Ταϊβάν)',
        'sl': 'kitajščina (tradicionalna pisava, Tajvan)',
        'uk': 'китайська (традиційна, Тайвань)',
        'ro': 'chineză (tradițională, Taiwan)',
        'ca': 'xinès (tradicional, Taiwan)',
        'ru': 'китайский (традиционная, Тайвань)',
        'bg': 'китайски (традиционна, Тайван)',
        'eu': 'txinera (tradizionala, Taiwan)',
        'ar': 'الصينية (التقليدية, تايوان)',
        'fa': 'چینی (سنتی, تایوان)',
        'sr': 'кинески (традиционално кинеско писмо, Тајван)',
        'es': 'chino (tradicional, Taiwán)',
        'fi': 'kiina (perinteinen, Taiwan)',
        'de': 'Chinesisch (Traditionell, Taiwan)',
        'da': 'kinesisk (traditionelt, Taiwan)',
        'zh_CN': '中文 (繁体, 台湾)',
        'is': 'kínverska (hefðbundið, Taívan)',
        'sr_RS@latin': 'кинески (традиционално кинеско писмо, Тајван)',
        'it': 'cinese (tradizionale, Taiwan)',
        'ko': '중국어 (번체, 대만)',
        'hy': 'չինարեն (ավանդական, Թայվան)',
        'gl': 'chinés (tradicional, Taiwán)',
        'fr': 'chinois (traditionnel, Taïwan)',
        'hu': 'kínai (Hagyományos, Tajvan)',
        'nb': 'kinesisk (tradisjonell, Taiwan)',
        'cs': 'čínština (tradiční, Tchaj-wan)',
        'ka': 'ჩინური (ტრადიციული, ტაივანი)',
        'sk': 'čínština (tradičné, Taiwan)',
        'id': 'Tionghoa (Tradisional, Taiwan)',
        'nl': 'Chinees (traditioneel, Taiwan)',
        'tr': 'Çince (Geleneksel, Tayvan)',
        'sv': 'kinesiska (traditionell, Taiwan)',
        'he': 'סינית (מסורתי, טייוואן)',
        'lt': 'kinų (tradiciniai, Taivanas)',
        'et': 'hiina (traditsiooniline, Taiwan)',
        'en': 'Chinese (Traditional, Taiwan)',
    },
}


completeness = {
    'ar': 37,
    'bg': 45,
    'ca': 70,
    'cs': 100,
    'da': 100,
    'de': 100,
    'el': 77,
    'en': 100,
    'eo': 100,
    'es': 100,
    'et': 100,
    'eu': 99,
    'fa': 62,
    'fi': 85,
    'fr': 100,
    'gl': 99,
    'he': 69,
    'hu': 84,
    'hy': 31,
    'id': 83,
    'is': 85,
    'it': 100,
    'ja': 99,
    'ka': 21,
    'ko': 73,
    'lo': 100,
    'lt': 100,
    'nb': 55,
    'nl': 99,
    'pl': 100,
    'pt': 100,
    'pt_BR': 100,
    'ro': 100,
    'ru': 97,
    'sk': 45,
    'sl': 55,
    'sr': 47,
    'sr_RS@latin': 45,
    'sv': 100,
    'tr': 85,
    'uk': 100,
    'zh_CN': 100,
    'zh_TW': 77,
}
