#!/bin/sh
# SPDX-FileCopyrightText: © 2008-2022 Oprea Dan
# SPDX-FileCopyrightText: © 2008-2022 Bart de Koning
# SPDX-FileCopyrightText: © 2008-2022 Richard Bailey
# SPDX-FileCopyrightText: © 2008-2022 Germar Reitze
# SPDX-FileCopyrightText: © 2017 Matthias Gerstner
# SPDX-FileCopyrightText: © 2024 Jürgen Altfeld
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of the program "Back In Time" which is released under GNU
# General Public License v2 (GPLv2). See LICENSES directory or go to
# <https://spdx.org/licenses/GPL-2.0-or-later.html>.

# fixing gray window error
# https://launchpad.net/bugs/1493020
export QT_GRAPHICSSYSTEM="native"

CUR_PATH="$(dirname $(readlink -m $0))"
if [ -f "${CUR_PATH}/app.py" ]; then
	APP_PATH=$CUR_PATH
else
	APP_PATH=$(readlink -m "${CUR_PATH}/../share/backintime/qt")
fi

/usr/bin/python3 -Es ${APP_PATH}/app.py "$@"
